# site name
prefixName:
siteName: 唯二主義
# favicon and site master avatar
favicon: /img/favicon/favicon.ico
avatar: /img/avatar/avatar.webp
url: https://vear.coding.me
description: 我们必须全力奔跑,才能停留在原地
cdn: https://cdn.jsdelivr.net/gh/vearvip/cdn@v0.0.12
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎来到我的个人博客
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  # 归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
  #   技术: {path: /categories/技术/, fa: fa-code }, 
  #   生活: {path: /categories/生活/, fa: fa-file-text-o }, 
  #   资源: {path: /categories/资源/, fa: fa-cloud-download }, 
  #   随想: {path: /categories/随想/, fa: fa-commenting-o },
  #   转载: {path: /categories/转载/, fa: fa-book }
  # } }
  技术: {path: /categories/技术/, fa: fa-code }
  生活: {path: /categories/生活/, fa: fa-file-text-o }
  图集: {path: /tags/图集/, fa: fa-photo }
  # 清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
  #   书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
  #   番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
  #   歌单: {path: /music/, fa: fa-headphones },
  #   图集: {path: /tags/图集/, fa: fa-photo }
  # } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  #   我？: {path: /about/, fa: fa-meetup}, 
  #   # 主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #   Lab: {path: /lab/, fa: fa-cogs },
  # } }
  关于我: {path: /about/, fa: fa-meetup}
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/vearvip/cdn@v0.0.12/img/carousel/江南烧酒.webp
  - https://cdn.jsdelivr.net/gh/vearvip/cdn@v0.0.12/img/carousel/绿森冒险者.webp
  - https://cdn.jsdelivr.net/gh/vearvip/cdn@v0.0.12/img/carousel/红枫林武士.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
# startdash: 
#   - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
#   - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
#   - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
  github: {url: https://github.com/vearvip, img: /img/icon/github.png}
  sina: {url: https://weibo.com/u/2911718935, img: /img/icon/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=291120746, img: /img/icon/wangyiyun.png}
  # zhihu: {url: https://cdn.jsdelivr.net/gh/vearvip/cdn@v0.0.12, img: /img/icon/zhihu.png}
  email: {url: mailto:vear.vip@qq.com, img: /img/icon/email.svg}
  wechat: {qrcode: /img/icon/wxcode.jpg, img: /img/icon/wechat.png}

#social  url, img 移动端配置
#娘的这个fa: fa-qq是 font_awesome的css icon图标，哎
msocial:
  github: {url: https://github.com/vearvip, fa: fa-github-alt, color: 333}
  email: {url: mailto:vear.vip@qq.com, fa: fa-envelope, color: ffb437}
  wechat: {fa: fa-wechat, color: 7ad447, qrcode: /img/icon/wxcode.jpg}

# 赞赏
donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: Mi8E75plXgSMdTolbgPQMNJu-gzGzoHsz
v_appKey: ngs85t38QzDBnLBJLRIr2o4p

